const CountryActionTypes = {
    FETCH_COUNTRY_START: 'FETCH_COUNTRY_START',
    FETCH_COUNTRY_SUCCESS: 'FETCH_COUNTRY_SUCCESS',
    FETCH_COUNTRY_FAILURE: 'FETCH_COUNTRY_FAILURE',
    FETCH_WEATHER_START: 'FETCH_WEATHER_START',
    FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
    FETCH_WEATHER_FAILURE: 'FETCH_WEATHER_FAILURE'
};

export default CountryActionTypes;